parameters:
  http.views.dir: '../www/views'
  dispatcher.separator: '/'
  beanstalk.connection.name: 'beanstalk'

services:
  api.config.storage.phalcon:
    decorates: api.config.storage
    decoration_priority: 100
    class: Vain\Phalcon\Api\Config\Storage\PhalconApiConfigStorage
    arguments: ['@api.config.storage.phalcon.inner', '@app.router']
  app.di:
    class: Vain\Phalcon\Di\Symfony\SymfonyContainerAdapter
    arguments: ['@service_container']
  app.bootstrapper.factory.mvc:
    public: true
    class: Vain\Phalcon\Bootstrapper\Factory\MvcBootstrapperFactory
  app.bootstrapper.factory.cli:
    public: true
    class: Vain\Phalcon\Bootstrapper\Factory\CliBootstrapperFactory
  app.router:
    class: Phalcon\Mvc\Router
    arguments: [false]
  router: '@app.router'
  app.dispatcher:
    class: Vain\Phalcon\Dispatcher\Mvc\MvcDispatcher
    arguments: ['%dispatcher.separator%']
    calls:
      - [setEventsManager, ['@event.manager']]
      - [setParams, [[]]]
  dispatcher: '@app.dispatcher'
  app.model.manager:
    class: Vain\Phalcon\Mvc\Model\PhalconModelManager
    calls:
      - [setEventsManager, ['@event.manager']]
      - [setDI, ['@app.di']]
  modelsManager: '@app.model.manager'
  app.modelsMetadata:
    class: Phalcon\Mvc\Model\MetaData\Memory
  modelsMetadata: '@app.modelsMetadata'
  app.mvc.phalcon:
    class: Phalcon\Mvc\Application
    arguments: ['@app.di']
  http.application:
    class: Vain\Phalcon\Application\Mvc\PhalconApplication
    arguments: ['@app.mvc.phalcon', '@http.response.proxy']
  app.mvc: '@http.application'
  app.escaper:
    class: Phalcon\Escaper
  escaper: '@app.escaper'
  app.security:
    class: Phalcon\Security
  security: '@app.security'
  app.crypt:
    class: Phalcon\Crypt
  crypt: '@app.crypt'
  app.annotations:
    class: Phalcon\Annotations\Adapter\Memory
  annotaions: '@app.annotations'
  app.tag:
    class: Phalcon\Tag
  tag: '@app.tag'
  app.session:
    class: Phalcon\Session\Adapter\Files
  session: '@app.session'
  app.session.bag:
    class: Phalcon\Session\Bag
  sessionBag: '@app.session.bag'
  app.transaction.manager:
    class: Phalcon\Mvc\Model\Transaction\Manager
    arguments: ['@app.di']
  transactionManager: '@app.transaction.manager'
  app.assets:
    class: Phalcon\Assets\Manager
  assets: '@app.assets'
  event.dispatcher.phalcon:
    decorates: event.dispatcher
    decoration_priority: 100
    class: Vain\Phalcon\Event\Dispatcher\PhalconEventDispatcher
    arguments: ['@event.dispatcher.phalcon.inner']
  eventManager: '@event.dispatcher'
  event.manager: '@event.dispatcher'
  http.filter:
    class: Phalcon\Filter
  filter: '@http.filter'
  http.header.factory:
    class: Vain\Phalcon\Http\Header\Factory\PhalconHeaderFactory
  http.header.provider: '@http.header.provider.server'
  http.cookie.factory:
    class: Vain\Phalcon\Http\Cookie\Factory\PhalconCookieFactory
  http.factory:
    class: Vain\Phalcon\Http\Factory\PhalconHttpFactory
    arguments: ['@http.filter', '@http.header.provider','@http.cookie.factory' ,'@http.header.factory']
  http.response.proxy:
    class: Vain\Phalcon\Http\Response\Proxy\PhalconResponseProxy
  response: '@http.response.proxy'
  http.response.factory: '@http.factory'
  http.request.proxy:
    class: Vain\Phalcon\Http\Request\Proxy\PhalconRequestProxy
  request: '@http.request.proxy'
  http.request.factory: '@http.factory'
  http.view:
    class: Phalcon\Mvc\View
    calls:
      - [setViewsDir, ['%http.views.dir%']]
      - [registerEngines, [{'.phtml': 'http.engine.php','.php': 'http.engine.php','.volt': 'http.engine.volt'}]]
  view: '@http.view'
  http.engine.php:
    class: Phalcon\Mvc\View\Engine\Php
    arguments: ['@http.view', '@app.di']
  http.engine.volt:
    class: Phalcon\Mvc\View\Engine\Volt
    arguments: ['@http.view', '@app.di']
  http.url:
    class: Phalcon\Mvc\Url
  url: '@http.url'
  http.cookie.storage:
    class: Vain\Phalcon\Http\Cookie\Storage\PhalconCookieStorage
    arguments: ['@http.cookie.factory']
  cookies:
    class: Phalcon\Http\Response\Cookies
  http.flash:
    class: Phalcon\Flash\Direct
  flash: '@http.flash'
  http.flash.session:
    class: Phalcon\Flash\Session
  flashSession: '@http.flash.session'
  entity.operation.factory.phalcon:
    parent: entity.operation.factory.abstract
    class: Vain\Phalcon\Entity\Operation\Factory\PhalconEntityOperationFactory
  database.factory.phalcon:
    class: Vain\Phalcon\Database\Factory\PhalconDatabaseFactory
    arguments: ['phalcon', '@database.generator.factory']
    tags:
      - {name: database.factory}
  api.config.parameter.factory.url:
    class: Vain\Phalcon\Api\Config\Parameter\Source\Factory\ApiConfigParameterUrlFactory
    arguments: ['@app.dispatcher']
    tags:
        - {name: source.factory}
  http.request: '@http.request.proxy'
  http.response: '@http.response.proxy'
  connection.beanstalk:
    parent: connection.abstract
    class: Vain\Phalcon\Queue\Beanstalk\BeanstalkConnection
    arguments: ['%beanstalk.connection.name%']
    tags:
      - {name: connection}
  queue.factory.beanstalk:
    class: Vain\Phalcon\Queue\Beanstalk\Factory\BeanstalkQueueFactory
    arguments: ['beanstalk', '@queue.message.factory.storage']
    tags:
      - {name: queue.factory}